#!/bin/sh -eux

# iTerm color schema
ghq get https://github.com/t3chnoboy/thayer-bright-iTerm

# ergodox keymap
ghq get https://github.com/jackhumbert/qmk_firmware.git

# vim
ghq get https://github.com/jnurmine/Zenburn.git
ghq get https://github.com/junegunn/vim-plug.git

# fisherman
ghq get https://github.com/fisherman/fisherman.git
# fisher oh-my-fish/theme-agnoster doesn't work
ghq get https://github.com/oh-my-fish/theme-agnoster.git

