#!/bin/sh -eux

XHOME=$(dirname $0)

ask() {
  printf "$* [y/n] "
  local answer
  read answer

  case $answer in
    "yes" ) return 0 ;;
    "y" )   return 0 ;;
    * )     return 1 ;;
  esac
}


$XHOME/prepare

if ask 'commandline tool?'; then
  $XHOME/xcode
fi

if ask 'homebrew?'; then
  $XHOME/homebrew
fi

if ask 'symlink?'; then
  $XHOME/symlink
fi

if ask 'ghq?'; then
  $XHOME/ghq
  $XHOME/vim
  $XHOME/fish
fi

