#!/bin/sh -eux

# env
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export HOMEBREW_BREWFILE=~/.brewfile/Brewfile

# ghq root
mkdir -p $HOME/src

# atom config dir
mkdir -p $HOME/.atom

# Sublime Text 3 config dir
mkdir -p $HOME/Library/Application\ Support/Sublime\ Text\ 3/

# screenshot dir
mkdir -p $HOME/Documents/screenshots

